// Report generation: HTML -> PDF (expo-print), and email submission (expo-mail-composer).
import * as Print from "expo-print";
import * as MailComposer from "expo-mail-composer";
import * as Sharing from "expo-sharing";
import { Linking, Platform } from "react-native";
import { Shift } from "@/src/lib/store";

export const DM_EMAIL = "dm@sphr.com.au";

function esc(s: string): string {
  return (s || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

export function buildReportHtml(shift: Shift): string {
  const rows = shift.entries
    .map((e, i) => {
      const gps =
        e.latitude != null && e.longitude != null
          ? `${e.latitude.toFixed(5)}, ${e.longitude.toFixed(5)}`
          : "—";
      const photo = e.photo
        ? `<div><img src="${e.photo}" style="max-width:160px;border-radius:6px;margin-top:6px"/></div>`
        : "";
      return `<tr>
        <td>${i + 1}</td>
        <td><strong>${esc(e.location)}</strong></td>
        <td>${esc(e.action)}${photo}</td>
        <td>${esc(e.time_label || "")}</td>
        <td>${gps}</td>
      </tr>`;
    })
    .join("");

  return `<!DOCTYPE html><html><head><meta charset="utf-8"/>
  <style>
    body{font-family:-apple-system,Helvetica,Arial,sans-serif;color:#101112;padding:24px}
    h1{color:#101112;margin:0 0 4px}
    .brand{color:#D88D16}
    .meta{margin:16px 0;padding:12px 16px;background:#f5f5f5;border-radius:8px}
    .meta div{margin:3px 0;font-size:13px}
    table{width:100%;border-collapse:collapse;margin-top:12px;font-size:12px}
    th{background:#101112;color:#fff;text-align:left;padding:8px}
    td{border-bottom:1px solid #e0e0e0;padding:8px;vertical-align:top}
    .foot{margin-top:24px;font-size:11px;color:#888}
  </style></head><body>
  <h1>SPHR <span class="brand">Night Patrol Report</span></h1>
  <div class="meta">
    <div><strong>Security Number:</strong> ${esc(shift.security_number)}</div>
    <div><strong>Guard Name:</strong> ${esc(shift.guard_name)}</div>
    <div><strong>Shift Date:</strong> ${esc(shift.shift_date)}</div>
    <div><strong>Manager on Diversion:</strong> ${esc(shift.manager_name || "—")} ${
    shift.manager_mobile ? "(" + esc(shift.manager_mobile) + ")" : ""
  }</div>
    <div><strong>Total Patrol Entries:</strong> ${shift.entries.length}</div>
  </div>
  <table>
    <thead><tr><th>#</th><th>Location</th><th>Action Taken</th><th>Time</th><th>GPS</th></tr></thead>
    <tbody>${rows || `<tr><td colspan="5">No patrol entries recorded.</td></tr>`}</tbody>
  </table>
  <div class="foot">Generated by SPHR Security Log App · ${new Date().toLocaleString()}</div>
  </body></html>`;
}

export function buildPlainText(shift: Shift): string {
  const lines = shift.entries.map(
    (e, i) =>
      `${i + 1}. [${e.time_label || ""}] ${e.location} — ${e.action}` +
      (e.latitude != null ? ` (GPS ${e.latitude.toFixed(5)}, ${e.longitude?.toFixed(5)})` : "")
  );
  return [
    `SPHR NIGHT PATROL REPORT`,
    `Security Number: ${shift.security_number}`,
    `Guard Name: ${shift.guard_name}`,
    `Shift Date: ${shift.shift_date}`,
    `Manager on Diversion: ${shift.manager_name || "—"}${
      shift.manager_mobile ? " (" + shift.manager_mobile + ")" : ""
    }`,
    `Total Entries: ${shift.entries.length}`,
    ``,
    `PATROL LOG:`,
    ...(lines.length ? lines : ["No entries recorded."]),
  ].join("\n");
}

export async function exportPdf(shift: Shift): Promise<string> {
  const html = buildReportHtml(shift);
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: "SPHR Night Patrol Report",
      UTI: "com.adobe.pdf",
    });
  }
  return uri;
}

// Returns "sent" | "composer" | "mailto"
export async function submitReport(shift: Shift): Promise<string> {
  const subject = `SPHR Night Patrol Report — ${shift.guard_name} — ${shift.shift_date}`;
  const body = buildPlainText(shift);

  const available =
    Platform.OS !== "web" && (await MailComposer.isAvailableAsync().catch(() => false));

  if (available) {
    const html = buildReportHtml(shift);
    let attachments: string[] = [];
    try {
      const { uri } = await Print.printToFileAsync({ html });
      attachments = [uri];
    } catch {
      attachments = [];
    }
    await MailComposer.composeAsync({
      recipients: [DM_EMAIL],
      subject,
      body,
      attachments,
    });
    return "composer";
  }

  // Fallback: open the phone's mail app pre-filled.
  const url = `mailto:${DM_EMAIL}?subject=${encodeURIComponent(
    subject
  )}&body=${encodeURIComponent(body)}`;
  await Linking.openURL(url);
  return "mailto";
}
